[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''
on_i = 1

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''
on_i = 1

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1
depends = ['deoplete.nvim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/neco-vim'
on_i = 1
on_ft = ['vim']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
    let g:go_fmt_command = "goimports"
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_types = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = ['Calendar']
hook_source = '''
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
'''

[[plugins]]
repo = 'magicalbanana/sql-syntax-vim'
on_ft = ['sql']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_source = '''
  autocmd BufRead,BufNewFile *.mkd  set filetype=markdown
  autocmd BufRead,BufNewFile *.md  set filetype=markdown
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''
  nnoremap <C-p> :PrevimOpen<cr>
  let g:previm_disable_default_css = 1
  let g:previm_custom_css_path = '~/dotfiles/.vim/templates/previm/markdown.css'
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
